// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"product-api-microservice-client/models"
)

// NewCreateProductsParams creates a new CreateProductsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateProductsParams() *CreateProductsParams {
	return &CreateProductsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProductsParamsWithTimeout creates a new CreateProductsParams object
// with the ability to set a timeout on a request.
func NewCreateProductsParamsWithTimeout(timeout time.Duration) *CreateProductsParams {
	return &CreateProductsParams{
		timeout: timeout,
	}
}

// NewCreateProductsParamsWithContext creates a new CreateProductsParams object
// with the ability to set a context for a request.
func NewCreateProductsParamsWithContext(ctx context.Context) *CreateProductsParams {
	return &CreateProductsParams{
		Context: ctx,
	}
}

// NewCreateProductsParamsWithHTTPClient creates a new CreateProductsParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateProductsParamsWithHTTPClient(client *http.Client) *CreateProductsParams {
	return &CreateProductsParams{
		HTTPClient: client,
	}
}

/*
CreateProductsParams contains all the parameters to send to the API endpoint

	for the create products operation.

	Typically these are written to a http.Request.
*/
type CreateProductsParams struct {

	// Body.
	Body *models.Product

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateProductsParams) WithDefaults() *CreateProductsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateProductsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create products params
func (o *CreateProductsParams) WithTimeout(timeout time.Duration) *CreateProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create products params
func (o *CreateProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create products params
func (o *CreateProductsParams) WithContext(ctx context.Context) *CreateProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create products params
func (o *CreateProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create products params
func (o *CreateProductsParams) WithHTTPClient(client *http.Client) *CreateProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create products params
func (o *CreateProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create products params
func (o *CreateProductsParams) WithBody(body *models.Product) *CreateProductsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create products params
func (o *CreateProductsParams) SetBody(body *models.Product) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
