// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"product-api-microservice-client/models"
)

// CreateProductsReader is a Reader for the CreateProducts structure.
type CreateProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewCreateProductsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /products] createProducts", response, response.Code())
	}
}

// NewCreateProductsOK creates a CreateProductsOK with default headers values
func NewCreateProductsOK() *CreateProductsOK {
	return &CreateProductsOK{}
}

/*
CreateProductsOK describes a response with status code 200, with default header values.

A list of Products
*/
type CreateProductsOK struct {
	Payload []*models.Product
}

// IsSuccess returns true when this create products o k response has a 2xx status code
func (o *CreateProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create products o k response has a 3xx status code
func (o *CreateProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create products o k response has a 4xx status code
func (o *CreateProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create products o k response has a 5xx status code
func (o *CreateProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create products o k response a status code equal to that given
func (o *CreateProductsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create products o k response
func (o *CreateProductsOK) Code() int {
	return 200
}

func (o *CreateProductsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductsOK %s", 200, payload)
}

func (o *CreateProductsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductsOK %s", 200, payload)
}

func (o *CreateProductsOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *CreateProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateProductsInternalServerError creates a CreateProductsInternalServerError with default headers values
func NewCreateProductsInternalServerError() *CreateProductsInternalServerError {
	return &CreateProductsInternalServerError{}
}

/*
CreateProductsInternalServerError describes a response with status code 500, with default header values.

CreateProductsInternalServerError create products internal server error
*/
type CreateProductsInternalServerError struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this create products internal server error response has a 2xx status code
func (o *CreateProductsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create products internal server error response has a 3xx status code
func (o *CreateProductsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create products internal server error response has a 4xx status code
func (o *CreateProductsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create products internal server error response has a 5xx status code
func (o *CreateProductsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create products internal server error response a status code equal to that given
func (o *CreateProductsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create products internal server error response
func (o *CreateProductsInternalServerError) Code() int {
	return 500
}

func (o *CreateProductsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductsInternalServerError %s", 500, payload)
}

func (o *CreateProductsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /products][%d] createProductsInternalServerError %s", 500, payload)
}

func (o *CreateProductsInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *CreateProductsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
