// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"product-api-microservice-client/models"
)

// NewUpdateProductsParams creates a new UpdateProductsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateProductsParams() *UpdateProductsParams {
	return &UpdateProductsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateProductsParamsWithTimeout creates a new UpdateProductsParams object
// with the ability to set a timeout on a request.
func NewUpdateProductsParamsWithTimeout(timeout time.Duration) *UpdateProductsParams {
	return &UpdateProductsParams{
		timeout: timeout,
	}
}

// NewUpdateProductsParamsWithContext creates a new UpdateProductsParams object
// with the ability to set a context for a request.
func NewUpdateProductsParamsWithContext(ctx context.Context) *UpdateProductsParams {
	return &UpdateProductsParams{
		Context: ctx,
	}
}

// NewUpdateProductsParamsWithHTTPClient creates a new UpdateProductsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateProductsParamsWithHTTPClient(client *http.Client) *UpdateProductsParams {
	return &UpdateProductsParams{
		HTTPClient: client,
	}
}

/*
UpdateProductsParams contains all the parameters to send to the API endpoint

	for the update products operation.

	Typically these are written to a http.Request.
*/
type UpdateProductsParams struct {

	// Body.
	Body *models.Product

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateProductsParams) WithDefaults() *UpdateProductsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update products params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateProductsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update products params
func (o *UpdateProductsParams) WithTimeout(timeout time.Duration) *UpdateProductsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update products params
func (o *UpdateProductsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update products params
func (o *UpdateProductsParams) WithContext(ctx context.Context) *UpdateProductsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update products params
func (o *UpdateProductsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update products params
func (o *UpdateProductsParams) WithHTTPClient(client *http.Client) *UpdateProductsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update products params
func (o *UpdateProductsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update products params
func (o *UpdateProductsParams) WithBody(body *models.Product) *UpdateProductsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update products params
func (o *UpdateProductsParams) SetBody(body *models.Product) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateProductsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
