// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"product-api-microservice-client/models"
)

// UpdateProductsReader is a Reader for the UpdateProducts structure.
type UpdateProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateProductsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateProductsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateProductsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /products] updateProducts", response, response.Code())
	}
}

// NewUpdateProductsOK creates a UpdateProductsOK with default headers values
func NewUpdateProductsOK() *UpdateProductsOK {
	return &UpdateProductsOK{}
}

/*
UpdateProductsOK describes a response with status code 200, with default header values.

A list of Products
*/
type UpdateProductsOK struct {
	Payload []*models.Product
}

// IsSuccess returns true when this update products o k response has a 2xx status code
func (o *UpdateProductsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update products o k response has a 3xx status code
func (o *UpdateProductsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update products o k response has a 4xx status code
func (o *UpdateProductsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update products o k response has a 5xx status code
func (o *UpdateProductsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update products o k response a status code equal to that given
func (o *UpdateProductsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update products o k response
func (o *UpdateProductsOK) Code() int {
	return 200
}

func (o *UpdateProductsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsOK %s", 200, payload)
}

func (o *UpdateProductsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsOK %s", 200, payload)
}

func (o *UpdateProductsOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *UpdateProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductsBadRequest creates a UpdateProductsBadRequest with default headers values
func NewUpdateProductsBadRequest() *UpdateProductsBadRequest {
	return &UpdateProductsBadRequest{}
}

/*
UpdateProductsBadRequest describes a response with status code 400, with default header values.

UpdateProductsBadRequest update products bad request
*/
type UpdateProductsBadRequest struct {
	Payload *models.ValidationError
}

// IsSuccess returns true when this update products bad request response has a 2xx status code
func (o *UpdateProductsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update products bad request response has a 3xx status code
func (o *UpdateProductsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update products bad request response has a 4xx status code
func (o *UpdateProductsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update products bad request response has a 5xx status code
func (o *UpdateProductsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update products bad request response a status code equal to that given
func (o *UpdateProductsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update products bad request response
func (o *UpdateProductsBadRequest) Code() int {
	return 400
}

func (o *UpdateProductsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsBadRequest %s", 400, payload)
}

func (o *UpdateProductsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsBadRequest %s", 400, payload)
}

func (o *UpdateProductsBadRequest) GetPayload() *models.ValidationError {
	return o.Payload
}

func (o *UpdateProductsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductsNotFound creates a UpdateProductsNotFound with default headers values
func NewUpdateProductsNotFound() *UpdateProductsNotFound {
	return &UpdateProductsNotFound{}
}

/*
UpdateProductsNotFound describes a response with status code 404, with default header values.

UpdateProductsNotFound update products not found
*/
type UpdateProductsNotFound struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this update products not found response has a 2xx status code
func (o *UpdateProductsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update products not found response has a 3xx status code
func (o *UpdateProductsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update products not found response has a 4xx status code
func (o *UpdateProductsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update products not found response has a 5xx status code
func (o *UpdateProductsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update products not found response a status code equal to that given
func (o *UpdateProductsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update products not found response
func (o *UpdateProductsNotFound) Code() int {
	return 404
}

func (o *UpdateProductsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsNotFound %s", 404, payload)
}

func (o *UpdateProductsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsNotFound %s", 404, payload)
}

func (o *UpdateProductsNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateProductsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateProductsInternalServerError creates a UpdateProductsInternalServerError with default headers values
func NewUpdateProductsInternalServerError() *UpdateProductsInternalServerError {
	return &UpdateProductsInternalServerError{}
}

/*
UpdateProductsInternalServerError describes a response with status code 500, with default header values.

UpdateProductsInternalServerError update products internal server error
*/
type UpdateProductsInternalServerError struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this update products internal server error response has a 2xx status code
func (o *UpdateProductsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update products internal server error response has a 3xx status code
func (o *UpdateProductsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update products internal server error response has a 4xx status code
func (o *UpdateProductsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update products internal server error response has a 5xx status code
func (o *UpdateProductsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update products internal server error response a status code equal to that given
func (o *UpdateProductsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update products internal server error response
func (o *UpdateProductsInternalServerError) Code() int {
	return 500
}

func (o *UpdateProductsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsInternalServerError %s", 500, payload)
}

func (o *UpdateProductsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /products][%d] updateProductsInternalServerError %s", 500, payload)
}

func (o *UpdateProductsInternalServerError) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *UpdateProductsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
